package com.example.cotacaofacil.domain.exception

class EmptyFildException() : Exception()
class PasswordLenghtException() : Exception()
class PasswordNotConfirmException() : Exception()
class UserTypeEmptyException() : Exception()
class CnpjInvalidException(private val errorMessage : String) : Exception(errorMessage)
class CnpjExistingException() : Exception()
class EmailInvalidException : Exception()
class NoConnectionInternetException() : Exception()
class DefaultException() : Exception()
class EmailOrPasswordInvalidException() : Exception()
class EmailExistingException() : Exception()
class CnpjIncompleteException() : Exception()
class CnpjOwnException() : Exception()
class UserNotFindException() : Exception()
class ErrorSaveBodyCompany() : Exception()
class PartnerRequestNotSendException() : Exception()
class NotRejectException() : Exception()
class RequestPartnerNotAccept() : Exception()
class CnpjExistingExceptionResponse() : Exception()
class HistoricEmptyException() : Exception()
class SaveDataEmptyConfirmationException() : Exception()
class ListEmptyException() : Exception()
class ScheduleDateForPastException() : Exception()
class StLeastOneHourException() : Exception()
class StLeastOneDayException() : Exception()
class MinTwoProvidersInPriceException() : Exception()
class PriorityIsEmptyException() : Exception()
class ErrorSaveProductException() : Exception()
class DateCurrentExceptions() : Exception()
class NotCreatePriceException() : Exception()